# Generated by Django 4.2.2 on 2023-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restwork', '0003_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
